// <auto-generated />
using HotDrinksMachine.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotDrinksMachine.Server.Migrations
{
    [DbContext(typeof(HotDrinksMachineDbContext))]
    [Migration("20211206114835_SeedDbData")]
    partial class SeedDbData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotDrinksMachine.Shared.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lemon Tea"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chocolate"
                        });
                });

            modelBuilder.Entity("HotDrinksMachine.Shared.Entities.DrinkPreparationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionOrder")
                        .HasColumnType("int");

                    b.Property<int>("DrinkId")
                        .HasColumnType("int");

                    b.Property<int>("PreparationActionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("PreparationActionId");

                    b.ToTable("DrinkPreparationActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionOrder = 1,
                            DrinkId = 1,
                            PreparationActionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionOrder = 2,
                            DrinkId = 1,
                            PreparationActionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionOrder = 3,
                            DrinkId = 1,
                            PreparationActionId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActionOrder = 4,
                            DrinkId = 1,
                            PreparationActionId = 4
                        },
                        new
                        {
                            Id = 5,
                            ActionOrder = 1,
                            DrinkId = 2,
                            PreparationActionId = 1
                        },
                        new
                        {
                            Id = 6,
                            ActionOrder = 2,
                            DrinkId = 2,
                            PreparationActionId = 5
                        },
                        new
                        {
                            Id = 7,
                            ActionOrder = 3,
                            DrinkId = 2,
                            PreparationActionId = 6
                        },
                        new
                        {
                            Id = 8,
                            ActionOrder = 4,
                            DrinkId = 2,
                            PreparationActionId = 7
                        },
                        new
                        {
                            Id = 9,
                            ActionOrder = 1,
                            DrinkId = 3,
                            PreparationActionId = 1
                        },
                        new
                        {
                            Id = 10,
                            ActionOrder = 2,
                            DrinkId = 3,
                            PreparationActionId = 8
                        },
                        new
                        {
                            Id = 11,
                            ActionOrder = 3,
                            DrinkId = 3,
                            PreparationActionId = 9
                        });
                });

            modelBuilder.Entity("HotDrinksMachine.Shared.Entities.PreparationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreparationActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Boil some water"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Steep the water in the tea"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pour tea in the cup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Add lemon"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Brew the coffee grounds"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pour coffee in the cup"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Add sugar and milk"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Add drinking chocolate powder to the water"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Pour chocolate in the cup"
                        });
                });

            modelBuilder.Entity("HotDrinksMachine.Shared.Entities.DrinkPreparationAction", b =>
                {
                    b.HasOne("HotDrinksMachine.Shared.Entities.Drink", null)
                        .WithMany("DrinkPreparationActions")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotDrinksMachine.Shared.Entities.PreparationAction", "PreparationAction")
                        .WithMany()
                        .HasForeignKey("PreparationActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreparationAction");
                });

            modelBuilder.Entity("HotDrinksMachine.Shared.Entities.Drink", b =>
                {
                    b.Navigation("DrinkPreparationActions");
                });
#pragma warning restore 612, 618
        }
    }
}
